=== varun070298/jag-6.1/templates/entity_facade_jboss_jsk_2_0/conf/conf-general/lib.dtd
<!ELEMENT libs (noInclude,war,ear)>
<!ELEMENT noInclude (lib|localLib)*>
<!ELEMENT war (lib|localLib)*>
<!ELEMENT ear (lib|localLib)*>
<!ELEMENT lib (#PCDATA)>
<!ATTLIST lib version CDATA #IMPLIED>
<!ATTLIST lib file CDATA #IMPLIED>
<!ATTLIST lib url CDATA #IMPLIED>
<!ELEMENT localLib (#PCDATA)>
<!ATTLIST localLib file CDATA #REQUIRED>

=== varun070298/jag-6.1/conf/lib.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE libs SYSTEM "lib.dtd">
<!--
   This file is used to checkout all dependent jars of JAG.
-->
<libs>
   <noInclude>
      <lib url="http://jag.sourceforge.net/download/jag/jars/jfreechart-common-1.0.0.jar"/>
      <lib url="http://www.ibiblio.org/maven/jfreechart/jars/jfreechart-1.0.0.jar"/>
      <lib url="http://www.ibiblio.org/maven/itext/jars/itext-1.3.1.jar"/>
      <lib url="http://www.ibiblio.org/maven/jasperreports/jars/jasperreports-1.2.0.jar"/>
      <lib url="http://jag.sourceforge.net/download/jag/jars/jdt-compiler-3.1.1.jar"/>
      
      <lib url="http://www.ibiblio.org/maven/commons-codec/jars/commons-codec-1.3.jar"/>
      <lib url="http://www.ibiblio.org/maven/commons-configuration/jars/commons-configuration-1.1.jar"/>
      <lib url="http://www.ibiblio.org/maven/commons-email/jars/commons-email-1.0.jar"/>
      <lib url="http://www.ibiblio.org/maven/commons-fileupload/jars/commons-fileupload-1.0.jar"/>
      <lib url="http://www.ibiblio.org/maven/commons-httpclient/jars/commons-httpclient-3.0.jar"/>
      <lib url="http://www.ibiblio.org/maven/commons-io/jars/commons-io-1.1.jar"/>
      <lib url="http://www.ibiblio.org/maven/commons-math/jars/commons-math-1.0.jar"/>
      <lib url="http://www.ibiblio.org/maven/commons-net/jars/commons-net-1.4.1.jar"/>
      <lib url="http://www.ibiblio.org/maven/jstl/jars/jstl-1.1.2.jar"/>
      <lib url="http://www.ibiblio.org/maven/taglibs/jars/standard-1.1.2.jar"/>
      <lib url="http://www.ibiblio.org/maven/org.apache.geronimo.specs/jars/geronimo-javamail_1.3.1_spec-1.0.jar"/>
      <lib url="http://www.ibiblio.org/maven/org.apache.geronimo.specs/jars/geronimo-activation_1.0.2_spec-1.0.jar"/>

      <lib url="http://www.ibiblio.org/maven/org.codehaus.xfire/jars/xfire-all-1.0.jar"/>
      <lib url="http://www.ibiblio.org/maven/org.apache.xbean/jars/xbean-spring-2.2.jar"/>
      <lib url="http://www.ibiblio.org/maven/jdom/jars/jdom-1.0.jar"/>
      <lib url="http://jag.sourceforge.net/download/jag/jars/xfire-jsr181-api-1.0-M1.jar"/>
      <lib url="http://www.ibiblio.org/maven/xmlbeans/jars/xbean-2.1.0.jar"/>
      <lib url="http://dist.codehaus.org/jaxen/jars/jaxen-1.1-beta-8.jar"/>
      <lib url="http://www.ibiblio.org/maven/woodstox/jars/wstx-asl-2.9.1.jar"/>
      <lib url="http://dist.codehaus.org/stax/jars/stax-api-1.0.jar"/>
      <lib url="http://www.ibiblio.org/maven/wsdl4j/jars/wsdl4j-1.5.2.jar"/>
      <lib url="http://www.ibiblio.org/maven/hivemind/jars/hivemind-1.1.1.jar"/>
      <lib url="http://www.ibiblio.org/maven/hivemind/jars/hivemind-lib-1.1.1.jar"/>
      <lib url="http://www.ibiblio.org/maven/javassist/jars/javassist-3.0.jar"/>
      <lib url="http://www.ibiblio.org/maven/ognl/jars/ognl-2.6.7.jar"/>
       
      <!-- Tapestry URLs. -->

      <lib url="http://jag.sourceforge.net/download/jag/jars/tacos4-beta-1-lib.jar"/>      
      <lib url="http://www.ibiblio.org/maven/tapestry/jars/tapestry-4.0.1.jar"/>
      <lib url="http://www.ibiblio.org/maven/tapestry/jars/tapestry-annotations-4.0.1.jar"/>
      <lib url="http://www.ibiblio.org/maven/tapestry/jars/tapestry-contrib-4.0.1.jar"/>
      <lib url="http://www.ibiblio.org/maven/tapestry/jars/tapestry-portlet-4.0.1.jar"/>

      <!-- UML Related jars -->
      <lib url="http://mmapps.sourceforge.net/distributions/mmapps/jars/simpleuml-1.0.1.jar"/>
      <lib url="http://jag.sourceforge.net/download/andromda.jar"/>
      <lib url="http://jag.sourceforge.net/download/jmi.jar"/>
      <lib url="http://jag.sourceforge.net/download/jmiuml14di.jar"/>
      <lib url="http://jag.sourceforge.net/download/jmiutils.jar"/>
      <lib url="http://jag.sourceforge.net/download/mdrapi.jar"/>
      <lib url="http://jag.sourceforge.net/download/mof.jar"/>
      <lib url="http://jag.sourceforge.net/download/nbmdr.jar"/>
      <lib url="http://jag.sourceforge.net/download/openide-lookup.jar"/>

      <lib url="http://jag.sourceforge.net/download/j2ee.jar"/>
      <lib url="http://jag.sourceforge.net/download/jars/checkstyle-all-4.0-beta4.jar"/>
      <lib url="http://jag.sourceforge.net/download/jars/jakarta-regexp-1.3.jar"/>
      <lib url="http://jag.sourceforge.net/download/checkstyle-noframes.xsl"/>
      <lib url="http://jag.sourceforge.net/download/checkstyle-frames.xsl"/>
      <lib url="http://jag.sourceforge.net/download/finalist_checks.xml"/>

      <lib url="http://jag.sourceforge.net/download/jars/ant-jmeter-2.0.3.jar"/>
      <lib url="http://www.ibiblio.org/maven/junit/jars/junit-3.8.1.jar"/>
      <lib url="http://www.ibiblio.org/maven/ant/jars/ant-optional-1.5.3-1.jar"/>
      <lib url="http://www.ibiblio.org/maven/emma/jars/emma-2.0.5312.jar"/>
      <lib url="http://www.ibiblio.org/maven/emma/jars/emma_ant-2.0.5312.jar"/>
      <lib url="http://www.ibiblio.org/maven/castor/jars/castor-0.9.7.jar"/>
      <lib url="http://www.ibiblio.org/maven/xdoclet/jars/xdoclet-1.2.jar"/>
      <lib url="http://www.ibiblio.org/maven/xdoclet/jars/xdoclet-xdoclet-module-1.2.jar"/>
      <lib url="http://www.ibiblio.org/maven/xdoclet/jars/xjavadoc-1.0.2.jar"/>
      <lib url="http://jag.sourceforge.net/download/jag/jars/xjavadoc-1.5-snapshot050611.jar"/>

      <!-- Appserver dependent Xdoclet tags -->
      <lib url="http://www.ibiblio.org/maven/xdoclet/jars/xdoclet-oracle-module-1.2.jar"/>
      <lib url="http://www.ibiblio.org/maven/xdoclet/jars/xdoclet-jboss-module-1.2.jar"/>

      <lib url="http://www.ibiblio.org/maven/xdoclet/jars/xdoclet-ejb-module-1.2.jar"/>
      <lib url="http://www.ibiblio.org/maven/xdoclet/jars/xdoclet-jmx-module-1.2.jar"/>
      <lib url="http://www.ibiblio.org/maven/xdoclet/jars/xdoclet-web-module-1.2.jar"/>
      <lib url="http://jag.sourceforge.net/download/jag/jars/xdoclet-apache-module-1.2.2.jar"/>
      <lib url="http://www.ibiblio.org/maven/xdoclet/jars/xdoclet-hibernate-module-1.2.jar"/>

      <!-- Database drivers -->
      <lib url="http://www.ibiblio.org/maven/postgresql/jars/postgresql-8.0-312.jdbc3.jar"/>
      <lib url="http://jag.sourceforge.net/download/jag/jars/mysql-connector-java-3.1.12-bin.jar"/>
      <lib url="http://www.ibiblio.org/maven/hsqldb/jars/hsqldb-1.7.3.3.jar"/>

      <lib url="http://jag.sourceforge.net/download/jag/jars/displaytag-1.1.jar"/>
      <lib url="http://jag.sourceforge.net/download/jag/jars/displaytag-export-poi-1.1.jar"/>
      <lib url="http://www.ibiblio.org/maven/poi/jars/poi-2.5.1.jar"/>

      <lib url="http://www.ibiblio.org/maven/velocity/jars/velocity-dep-1.4.jar"/>
      <lib url="http://www.ibiblio.org/maven/log4j/jars/log4j-1.2.8.jar"/>
      <lib url="http://www.ibiblio.org/maven/struts/jars/struts-1.2.4.jar"/>
      <lib url="http://www.ibiblio.org/maven/commons-beanutils/jars/commons-beanutils-1.7.0.jar"/>
      <lib url="http://www.ibiblio.org/maven/commons-collections/jars/commons-collections-3.1.jar"/>
      <lib url="http://www.ibiblio.org/maven/commons-digester/jars/commons-digester-1.7.jar"/>
      <lib url="http://www.ibiblio.org/maven/commons-lang/jars/commons-lang-2.1.jar"/>
      <lib url="http://www.ibiblio.org/maven/commons-logging/jars/commons-logging-1.0.4.jar"/>
      <lib url="http://www.ibiblio.org/maven/commons-validator/jars/commons-validator-1.1.3.jar"/>
      <lib url="http://www.ibiblio.org/maven/commons-discovery/jars/commons-discovery-0.2.jar"/>
      <lib url="http://www.ibiblio.org/maven/commons-attributes/jars/commons-attributes-api-2.1.jar"/>
      <lib url="http://www.ibiblio.org/maven/commons-attributes/jars/commons-attributes-compiler-2.1.jar"/>
      <lib url="http://www.ibiblio.org/maven/quartz/jars/quartz-1.5.1.jar"/>       
      <!-- JAG Modules -->
      <lib url="http://jag.sourceforge.net/download/jag/jars/finalist-ant-1.3.jar"/>
      <lib url="http://jag.sourceforge.net/download/jag/jars/errors-taglib-1.1.jar"/>
      <lib url="http://jag.sourceforge.net/download/jag/jars/generic-exceptions-struts-1.2.jar"/>
      <lib url="http://jag.sourceforge.net/download/jag/jars/finalist-taglib-1.0.jar"/>
      <lib url="http://jag.sourceforge.net/download/jag/jars/statementexecutor-1.1.jar"/>
      <lib url="http://jag.sourceforge.net/download/jag/jars/generic-exceptions-1.0.jar"/>
      <lib url="http://jag.sourceforge.net/download/jag/jars/sequencegenerator-ejb-1.0.jar"/>
      <lib url="http://jag.sourceforge.net/download/jag/jars/sequencegenerator-ejb-1.0-sunone-client.jar"/>
      <!-- A patched version of the sunone xdoclet jar to fix a CMR bug -->
      <lib url="http://jag.sourceforge.net/download/jag/jars/xdoclet-sun-module-1.2-cmr-patch.jar"/>
      <!-- A patched version to support weblogic 8.1 -->
      <lib url="http://jag.sourceforge.net/download/jag/jars/xdoclet-bea-module-1.2-patch.jar"/>

      <lib url="http://www.ibiblio.org/maven/asm/jars/asm-attrs-1.5.3.jar"/>
      <lib url="http://www.ibiblio.org/maven/asm/jars/asm-1.5.3.jar"/>

      <lib url="http://www.ibiblio.org/maven/antlr/jars/antlr-2.7.6.jar"/>

      <lib url="http://www.ibiblio.org/maven/org.hibernate/jars/hibernate-3.1.2.jar" />
      <lib url="http://www.ibiblio.org/maven/org.hibernate/jars/hibernate-annotations-3.1beta8.jar" />
      <lib url="http://jag.sourceforge.net/download/jag/jars/ejb3-persistence-3.1beta8.jar" />

      <lib url="http://jag.sourceforge.net/download/jars/ejb-3.0-edr2.jar" />
      <lib url="http://www.ibiblio.org/maven/hibernate/jars/hibernate-2.1.7c.jar"/>
      <lib url="http://www.ibiblio.org/maven/c3p0/jars/c3p0-0.9.0.jar"/>
      <lib url="http://www.ibiblio.org/maven/cglib/jars/cglib-2.1_3.jar"/>
      <lib url="http://www.ibiblio.org/maven/odmg/jars/odmg-3.0.jar"/>
      <lib url="http://www.ibiblio.org/maven/ehcache/jars/ehcache-0.9.jar"/>
      <lib url="http://www.ibiblio.org/maven/dom4j/jars/dom4j-1.6.1.jar"/>

       <!--
       The jta.jar should be download from the sun website.
       -->
      <lib url="http://java.sun.com/products/jta/jta1.0.1.jar"/>

       <!--
